---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dapr1-app-config
data:
  DAPR2_URL: http://dapr2.default.svc.cluster.local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "dapr1"
spec:
  selector:
    matchLabels:
      app: "dapr1"
  replicas: 2
  template:
    metadata:
      labels:
        app: "dapr1"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr1"
        dapr.io/app-port: "9011"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: "dapr1"
          image: "localhost:5000/dapr1:latest"
          ports:
            - containerPort: 9011
          env:
            - name: DAPR2_URL
              valueFrom:
                configMapKeyRef:
                  name: dapr1-app-config
                  key: DAPR2_URL

---

apiVersion: v1
kind: Service
metadata:
  name: "dapr1"
  labels:
    app: "dapr1"
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9011
      name: http
  selector:
    app: "dapr1"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dapr1-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dapr1
            port:
              number: 80
