apiVersion: v1
kind: Service
metadata:
  name: "dapr2"
  labels:
    app: "dapr2"
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9012
      name: http
  selector:
    app: "dapr2"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "dapr2"
spec:
  selector:
    matchLabels:
      app: "dapr2"
  replicas: 2
  template:
    metadata:
      labels:
        app: "dapr2"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr2"
        dapr.io/app-port: "9012"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: "dapr2"
          image: "localhost:5000/dapr2:latest"
          ports:
            - containerPort: 9012
         
